"""Ollama packaging backend.

Ollama does not *train* — this backend takes a fine-tuned checkpoint that
a training backend already produced (a merged 16-bit dir, or a GGUF file)
and registers it with Ollama via a generated Modelfile, so the result is
immediately usable with `ollama run`.

Typical flow:
    finetuner run --backend unsloth ... --save-merged   # train + merge
    finetuner run --backend ollama  --base-model <merged_dir> \\
        --model-name my-model --dataset <unused>        # package

Here ``base_model`` is the *path* to the merged checkpoint or GGUF, not an
HF id.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Any

from ..config import FinetuneConfig
from .base import Backend, write_summary


class OllamaBackend(Backend):
    """Register a trained checkpoint with Ollama via `ollama create`."""

    name = "ollama"

    def run(self, cfg: FinetuneConfig) -> dict[str, Any]:
        if shutil.which("ollama") is None:
            raise RuntimeError(
                "`ollama` is not on PATH — install Ollama (https://ollama.com) "
                "before using the ollama backend."
            )

        src = Path(cfg.base_model)
        if not src.exists():
            raise FileNotFoundError(
                f"checkpoint not found: {src}. For the ollama backend, "
                "--base-model must point at a merged checkpoint dir or a "
                "GGUF file produced by a training run."
            )

        out = Path(cfg.output_dir)
        out.mkdir(parents=True, exist_ok=True)
        modelfile = out / "Modelfile"
        # `FROM` accepts a GGUF path or a directory of safetensors.
        modelfile.write_text(
            f"# Generated by finetuner — Phagocyte Phase 6\n"
            f"FROM {src.resolve()}\n"
        )
        print(f"[ollama] Modelfile → {modelfile}")

        cmd = ["ollama", "create", cfg.model_name, "-f", str(modelfile)]
        print(f"[ollama] $ {' '.join(cmd)}")
        rc = subprocess.call(cmd)
        if rc != 0:
            raise RuntimeError(f"`ollama create` exited {rc}")

        result: dict[str, Any] = {
            "backend": "ollama",
            "model_name": cfg.model_name,
            "source": str(src.resolve()),
            "modelfile": str(modelfile),
            "run_with": f"ollama run {cfg.model_name}",
        }
        write_summary(cfg, result)
        print(f"[ollama] created model '{cfg.model_name}' — `ollama run {cfg.model_name}`")
        return result
